import { StyleSheet } from "react-native";
import { color } from "react-native-reanimated";
import { colorTheme } from "./color_constants";

export const event_style = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    // marginTop: 10,
    marginBottom: 95,
  },
  rolesContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    justifyContent: "space-evenly",
    marginHorizontal: 1,
    minHeight: "8%",
    height: "8%",
    alignItems: "center",
    backgroundColor: colorTheme.ultralight_secondary_color,
    borderBottomWidth: 1,
    borderColor: colorTheme.light_tertiary_color,
    paddingVertical: 10,
  },
  profileImage: {
    marginTop: 10,
    borderRadius: 35,
    width: 70,
    height: 70,
    borderWidth: 3,
    borderColor: colorTheme.button + "cc",

    alignSelf: "center",
  },
  role: {
    alignSelf: "center",
    minHeight: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 6,
    // borderBottomWidth: 1,
    // borderColor: colorTheme.tertiary_color,
    // backgroundColor: colorTheme.ultralight_secondary_color,
    flex: 2,
  },
  roleText: {
    textAlign: "center",
    fontSize: 15,
  },
  selectedRole: {
    borderBottomWidth: 2,
    borderRadius: 3,
    fontWeight: "bold",
    borderColor: colorTheme.light_tertiary_color,
  },
  dividersContainer: {
    backgroundColor: colorTheme.light_primary_color,
    justifyContent: "space-between",
    flexDirection: "row",
    minHeight: "8%",
    height: "8%",
    alignItems: "center",
  },
  divider: {
    // flex: 1,
    // backgroundColor: "white",
    // height: 40,
    // width: 95,
    // alignItems: "center",
    // justifyContent: "center",
    // borderRadius: 10,
    // marginRight: 1,
    // marginLeft: 1,
    alignSelf: "center",
    minHeight: "100%",
    alignItems: "center",
    justifyContent: "center",
    // borderWidth: 1,
    borderColor: colorTheme.tertiary_color,
    backgroundColor: colorTheme.light_primary_color,
    borderRadius: 0,
    flex: 2,
  },
  dividerText: {
    textAlign: "center",
    fontSize: 13,
    fontSize: 13,
  },
  selectedTab: {
    backgroundColor: colorTheme.light_secondary_color,
    borderRadius: 0,
    borderBottomWidth: 0,
  },
  fullWidthButton: {
    backgroundColor: colorTheme.button + "99",
    padding: 15,
    borderRadius: 30,
    borderWidth: 3,
    borderColor: colorTheme.button + "cc",
    alignItems: "center",
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  fullWidthButton1: {
    backgroundColor: colorTheme.button + "99",
    padding: 15,
    marginTop: 15,
    alignItems: "center",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderWidth: 3,
    borderColor: colorTheme.button + "cc",
  },
  fullWidthButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "500",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  listContentContainer: {
    paddingBottom: 20,
  },
  modalContent: {
    backgroundColor: "white",
    width: "90%",
    paddingHorizontal: 40,
    paddingTop: 20,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 10,
  },
  modalTextInput: {
    borderWidth: 1,
    borderColor: colorTheme.light_primary_color,
    padding: 10,
    marginBottom: "20%",
    borderRadius: 10,
    width: "100%",
  },
  modalDescriptionTextInput: {
    height: "30%",
    textAlignVertical: "top",
    fontSize: 14,
    padding: 15,
  },
  image: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 3,
    borderColor: colorTheme.button + "cc",
  },
  obcontainerRequest: {
    flex: 1,
    minWidth: "99%",
    maxWidth: "99%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colorTheme.secondary_color + "77",
    borderRadius: 5,
    marginBottom: 5,
    borderWidth: 2,
    borderColor: colorTheme.tertiary_color + "bb",
  },
  obcontainer: {
    flex: 1,
    minWidth: "99%",
    maxWidth: "99%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#dcdcdc",
    marginBottom: 5,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: "grey",
    paddingBottom: 10,
  },
  task: {
    flex: 1,
    minWidth: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  notificationHeader: {
    flex: 1,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: "grey",
    justifyContent: "center",
    alignContent: "center",
  },
  notificationHeaderImg: {
    flex: 1,
    padding: "3%",
    paddingRight: 0,
  },
  notificationHeaderText: {
    flex: 5,
    paddingTop: "3%",
  },
  ime: {
    fontSize: 18,
  },
  imekoor: {
    fontSize: 18,
    alignSelf: "center",
    color: colorTheme.primary_color,
    
    marginBottom: 10,
  },
  date: {},
  info: {
    fontSize: 18,
    // marginBottom:20,
    marginTop:10,
    alignSelf: "center",
    padding: 20,
  },
  nadlezan: {
    fontSize: 18,

    marginTop: 10,
    alignSelf: "center",
  },
  naslov: {
    flex: 1,
    fontSize: 20,
    // color: colorTheme.light_primary_color,
    paddingBottom: 20,
  },
  text: {
    flex: 1,
    fontSize: 14,
    // color: colorTheme.light_primary_color,
    // paddingBottom: 20,
    textAlign: "justify",
  },
  listContainer: {
    flex: 1,
    marginTop: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  textcontainer: {
    flex: 1,
    width: "100%",
    padding: 20,
    justifyContent: "space-around",
    // alignItems: "center",
    minHeight: "50%",
  },
  otimucontainer: {
    flex: 1,
  },
  editButton: {
    right: 0,
    backgroundColor: "red",
    padding: 5,
    borderRadius: 5,
  },
  editButtonContainer: {
    marginTop: 5,
    marginRight: 10,
  },
  disabledButton: {
    opacity: 0.5,
  },
  buttonmodal: {
    textAlign: "center",
    alignItems: "center",
    alignContent: "center",
    backgroundColor: colorTheme.button + "99",
    padding: 10,
    marginHorizontal: 5,
    borderRadius: 30,
    marginBottom: 10,
    borderWidth: 3,
    minWidth: "40%",
    borderColor: colorTheme.button + "cc",
    marginBottom:25
  },
  buttonText: {
    textAlign: "center",
    fontSize: 18,
    color: "white",
    fontWeight: "600",
  },
  buttons: {
    flexDirection: "column",
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 10,
    marginTop: 10,
  },
  pending: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    borderTopWidth: 1,
    borderRadius: 5,
    borderColor: colorTheme.tertiary_color + "bb",
    borderTopStartRadius: 0,
    borderTopEndRadius: 0,
    borderTopEndRadius: 0,
  },
  pendingYes: {
    flex: 1,
    width: "100%",
    height: "100%",
    padding: 10,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    backgroundColor: "#8bd165",
    borderColor: colorTheme.tertiary_color + "bb",
    borderRightWidth: 1,
    borderBottomStartRadius: 3,
  },
  pendingNo: {
    flex: 1,
    width: "100%",
    height: "100%",
    padding: 10,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    backgroundColor: "#ff493c",
    borderColor: colorTheme.tertiary_color + "bb",
    borderBottomRightRadius: 3,
    borderRightWidth: 1,
  },
  odustani: {
    textAlign: "center",
    fontSize: 16,
    color: "#000000aa",
    paddingVertical: 5,
    fontWeight: "500",
  },
  noImageContainer: {
    width: 70,
    height: 70,
    borderRadius: 35,
    alignSelf: "center",
    backgroundColor: "#ccc",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: colorTheme.button + "cc",
    marginTop: 10,
  },
  memberInitials: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
  },
  innerContainer: {
    padding: 20,
    
    alignItems: "center",
    
  },
});
