import { StyleSheet } from "react-native";
import { colorTheme } from "./color_constants";

export const meetings_style = StyleSheet.create({
  dividersContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    padding: 20,
  },
  divider: {
    backgroundColor: "white",
    height: 40,
    width: 95,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginRight: 1,
    marginLeft: 1,
  },
  dividerText: {
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
  },
  selectedTab: {
    backgroundColor: colorTheme.button,
  },
  addButton: {
    backgroundColor: "red",
    borderRadius: 5,
    padding: 10,
    margin: 10,
    alignSelf: "stretch",
  },
  addButtonText: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalContainer: {
    padding: 20,
    justifyContent: "center",
    backgroundColor: "white",
  },
  deleteModalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  buttonpass: {
    width: 200,
    backgroundColor: colorTheme.button,
    marginTop: 20,
  },
  deleteModalContent: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    margin: 50,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
  },
  memberContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },

  memberImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 10,
    borderWidth: 3,
    borderColor: colorTheme.button + "cc",
  },
  memberNameContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 5,
  },
  memberName: {
    fontSize: 18,
    fontWeight: "bold",
  },
  noImageContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 16,
    backgroundColor: "#ccc",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: colorTheme.button + "cc",
  },
  memberInitials: {
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
  },
  input: {
    borderWidth: 1,
    borderColor: colorTheme.light_primary_color,
    padding: 10,
    marginBottom: 10,
    borderRadius: 10,
    width: 250,
    marginTop: 15,
  },

  label: {
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 10,
  },
  label5: {
    fontSize: 16,
    fontWeight: "bold",
    
  },
  label3: {
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 10,
    marginBottom:10
  },

  button: {
    textAlign: "center",
    alignItems: "center",
    alignContent: "center",
    backgroundColor: colorTheme.button + "99",
    padding: 10,
    marginHorizontal: 5,
    borderRadius: 30,
    borderWidth: 3,
    borderColor: colorTheme.button + "cc",
    marginTop: 20,
    marginBottom: 10,
  },
  deleteButton: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginVertical: 10,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "white",
  },
  circleStyle: {
    width: 50,
    height: 50,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: "#ccc",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 5,
    marginHorizontal: 8,
  },
  selectedCircleStyle: {
    borderColor: colorTheme.light_primary_color,
    backgroundColor: colorTheme.button + "99",
  },
  circleText: {
    color: "#333",
    fontSize: 12,
  },
  selectedCircleText: {
    color: "white",
  },
  teamsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    marginTop: 10,
  },
  eventsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    marginTop: 10,
  },
  eventButton: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    margin: 5,
  },
  selectedEventStyle: {
    backgroundColor: "red",
  },
  datumiContainer: {},
  listItem: {
     alignSelf: "flex-start",
      padding: "4%" 
    },
  itemContainer: {
    flexDirection: "row",
    height: "100%",
    backgroundColor: colorTheme.ultralight_tertiary_color,
  },
  currentMeetingColor: colorTheme.ultralight_secondary_color,
  finishedMeetingColor: colorTheme.light_primary_color,
  itemStyle: {
    flexDirection: "column",
    justifyContent: "space-around",
    height: "100%",
    paddingRight: 20,
    paddingLeft: 20,
  },
  dateAndTeam: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomColor: "black",
    borderBottomWidth: 2,
  },
  dateAndTeam1: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomColor: colorTheme.button + "cc",
    borderBottomWidth: 2,
  },

  MoMinput: {
    borderWidth: 1,
    borderColor: colorTheme.light_primary_color,
    padding: 10,
    marginBottom: 10,
    borderRadius: 10,
    width: 250,
    marginTop: 15,
    marginRight: 20,
  },
  clickedMeetingModalContent: {
    justifyContent: "space-between",
    flex: 1,
    padding: 10,
  },
  confirmAttendanceBtn: {
    color: "green",
  },
  unconfirmAttendanceBtn: { color: "red" },
  attendees: {
    minHeight: 1,
  },
  buttonText: {
    textAlign: "center",
    fontSize: 18,
    color: "white",
    fontWeight: "600",
  },
  button1: {
    textAlign: "center",
    alignItems: "center",
    alignContent: "center",
    backgroundColor: colorTheme.button + "99",
    padding: 10,
    marginHorizontal: 5,
    borderRadius: 30,
    borderWidth: 3,
    borderColor: colorTheme.button + "cc",
    flex: 1,
  },
  label1: {
    marginTop: 30,
    fontSize: 16,
    marginBottom: 5,
    marginRight: 5,
  },
  label2: {
    marginTop: 30,
    fontSize: 14,
    marginBottom: 5,
    marginRight: 5,
  },
  description: {
    marginTop: 10,
    fontSize: 16,
    marginBottom: 5,
    marginRight: 5,
    color: colorTheme.primary_color,
  },
  buttons: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  label7: {
    marginTop: 30,
    fontSize: 16,
    marginBottom: 5,
    marginRight: 5,
    padding:20,
    alignSelf:"center",
    fontWeight: "600",
  },
});
